import os
import re
import sys

def amalgamate(root_file, out_file, include_paths):
    processed_files = set()
    std_includes = set()
    out_lines = []

    # Include guard for the amalgamated header
    out_lines.append("#ifndef CJSONX_SINGLE_HEADER_H\n")
    out_lines.append("#define CJSONX_SINGLE_HEADER_H\n\n")
    out_lines.append("// Amalgamated single-header version of cjsonx\n")
    out_lines.append("// Do not edit this file directly. Edit the source files in include/ and run scripts/amalgamate.py\n\n")

    def process_file(filepath):
        if filepath in processed_files:
            return
        processed_files.add(filepath)

        with open(filepath, 'r') as f:
            lines = f.readlines()

        for line in lines:
            # Handle standard library includes
            std_match = re.match(r'^\s*#include\s+<([^>]+)>', line)
            if std_match:
                std_inc = std_match.group(0)
                if std_inc not in std_includes:
                    std_includes.add(std_inc)
                    out_lines.append(line)
                continue

            # Handle local includes
            local_match = re.match(r'^\s*#include\s+"([^"]+)"', line)
            if local_match:
                inc_name = local_match.group(1)
                found = False
                for search_path in include_paths:
                    candidate = os.path.join(search_path, inc_name)
                    if os.path.exists(candidate):
                        out_lines.append(f"// --- Begin {inc_name} ---\n")
                        process_file(candidate)
                        out_lines.append(f"// --- End {inc_name} ---\n\n")
                        found = True
                        break
                if not found:
                    print(f"Warning: Could not find included file: {inc_name}")
                continue
            
            # Pragma once is handled by processed_files, but we can also strip standard include guards if we want
            # We'll just leave them since they are harmless and sometimes needed if extracted.
            out_lines.append(line)

    process_file(root_file)
    
    out_lines.append("\n#endif // CJSONX_SINGLE_HEADER_H\n")

    with open(out_file, 'w') as f:
        f.writelines(out_lines)
    
    print(f"Amalgamation complete: {out_file}")

if __name__ == "__main__":
    include_dirs = ["include"]
    root_header = "include/cjsonx.h"
    output_header = "single_include/cjsonx.h"
    
    if not os.path.exists("include"):
        print("Please run from the root of the project")
        sys.exit(1)
        
    amalgamate(root_header, output_header, include_dirs)
