name: Release Header

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Package Header
      run: |
        mkdir -p package
        cp single_include/cjsonx.h package/
        cd package
        zip -r ../cjsonx.zip .
        tar -czf ../cjsonx.tar.gz .

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          cjsonx.zip
          cjsonx.tar.gz
        generate_release_notes: true
